### ISSUE TITLE
Error in BetonQuest

### ISSUE THREAD

**Issue by HollishKid** [HollishKid/Gaia#110]
L'erreur suivant est lancée en parlant avec certains gardes royaux.
Serait-ce parce que les options joueurs sont vides ? 
EDIT : Non, même en ajoutant un pointer, ce n'est pas résolu.

`[20:03:04] [Craft Scheduler Thread - 2809/ERROR]: Could not pass event PlayerConversationStartEvent to BetonQuest v1.9-dev
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
at pl.betoncraft.betonquest.conversation.Conversation$Starter.run(Conversation.java:464) [BetonQuest-1.9-dev%23209-patched.jar:?]
at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.IllegalStateException: Asynchronous entity track!
at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
at net.minecraft.server.v1_9_R2.EntityTracker.addEntity(EntityTracker.java:104) ~[spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
at net.minecraft.server.v1_9_R2.EntityTracker.track(EntityTracker.java:90) ~[spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
at net.minecraft.server.v1_9_R2.WorldManager.a(WorldManager.java:19) ~[spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
at net.minecraft.server.v1_9_R2.World.b(World.java:1024) ~[spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
at net.minecraft.server.v1_9_R2.WorldServer.b(WorldServer.java:1126) ~[spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
at net.minecraft.server.v1_9_R2.WorldServer.a(WorldServer.java:1091) ~[spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
at net.minecraft.server.v1_9_R2.Chunk.addEntities(Chunk.java:757) ~[spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
at org.bukkit.craftbukkit.v1_9_R2.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:45) ~[spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
at org.bukkit.craftbukkit.v1_9_R2.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1) ~[spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
at org.bukkit.craftbukkit.v1_9_R2.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337) ~[spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
at org.bukkit.craftbukkit.v1_9_R2.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295) ~[spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
at org.bukkit.craftbukkit.v1_9_R2.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16) ~[spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
at net.minecraft.server.v1_9_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:128) ~[spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
at net.minecraft.server.v1_9_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:111) ~[spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
at net.minecraft.server.v1_9_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:107) ~[spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
at net.minecraft.server.v1_9_R2.World.getChunkAt(World.java:329) ~[spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
at net.minecraft.server.v1_9_R2.ChunkCache.(SourceFile:36) ~[spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
at net.citizensnpcs.util.nms.PlayerNavigation.a2(PlayerNavigation.java:280) ~[?:?]
at net.citizensnpcs.util.nms.PlayerNavigation.a(PlayerNavigation.java:83) ~[?:?]
at net.minecraft.server.v1_9_R2.NavigationAbstract.a(SourceFile:89) ~[spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
at net.citizensnpcs.util.nms.PlayerNavigation.a(PlayerNavigation.java:99) ~[?:?]
at net.citizensnpcs.npc.ai.MCNavigationStrategy.(MCNavigationStrategy.java:32) ~[?:?]
at net.citizensnpcs.npc.ai.CitizensNavigator.setTarget(CitizensNavigator.java:212) ~[?:?]
at pl.betoncraft.betonquest.compatibility.citizens.CitizensWalkingListener.onConversationStart(CitizensWalkingListener.java:65) ~[?:?]
at sun.reflect.GeneratedMethodAccessor474.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
... 9 more`

**Comment by HollishKid** [comment]
Ceci semble avoir été résolu avec le passage à MM.
Je ferme pour l'instant.
