### ISSUE TITLE
Crash BetonQuest

### ISSUE THREAD

**Issue by crashoz** [HollishKid/Gaia#37]
J'ai investigué les crashs BetonQuest qu'on a de temps en temps depuis le passage à la v1.9-dev#209. Ca survient quand un joueur a un objective "ACTION RIGHT" sur un block ou un object à réaliser.

Ca balance ceci

[14:51:35] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to BetonQuest v1.9-dev#209

org.bukkit.event.EventException

	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]

	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]

	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]

	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]

	at org.bukkit.craftbukkit.v1_9_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]

	at net.minecraft.server.v1_9_R2.PlayerInteractManager.a(PlayerInteractManager.java:483) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]

	at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:887) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]

	at net.minecraft.server.v1_9_R2.PacketPlayInUseItem.a(SourceFile:55) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]

	at net.minecraft.server.v1_9_R2.PacketPlayInUseItem.a(SourceFile:11) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]

	at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]

	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]

	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]

	at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]

	at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:726) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]

	at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]

	at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]

	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]

	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

Caused by: java.lang.NullPointerException

**Comment by HollishKid** [comment]
Ceci est dû sûrement à la nouvelle version de BetonQuest.
Un mail à été envoyé à Co0sh.

**Comment by crashoz** [comment]
C'était juste un probleme de conversion depuis la v48 (#205) vers la v51 (#209), donc pas de probleme dans BetonQuest. Il faut juste faire attention au passage v48 -> v51.
Je pense qu'on peut close cette issue
