### ISSUE TITLE
Erreur MyticMobs

### ISSUE THREAD

**Issue by HollishKid** [HollishKid/Gaia#92]
L'erreur suivante est spammée dans la console.

```
[02:58:29] [Craft Scheduler Thread - 16/WARN]: Exception in thread "Craft Scheduler Thread - 16"
[02:58:29] [Craft Scheduler Thread - 16/WARN]: org.apache.commons.lang.UnhandledException: Plugin MythicMobs v4.0.1 generated an exception while executing task 58
at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
at io.lumine.xikage.mythicmobs.mobs.EntityManager.getPlayersInRangeSq(EntityManager.java:67)
at io.lumine.xikage.mythicmobs.mobs.ActiveMob.updateBossBar(ActiveMob.java:421)
at io.lumine.xikage.mythicmobs.mobs.ActiveMob.tickGlobalCooldown(ActiveMob.java:222)
at io.lumine.xikage.mythicmobs.skills.AbstractSkill.RunTimerSkills(AbstractSkill.java:296)
at io.lumine.xikage.mythicmobs.clock.MythicMobsAsyncClock.run(MythicMobsAsyncClock.java:19)
at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71)
at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
... 3 more
```

**Comment by HollishKid** [comment]
Version plus récente et plus complète :
https://pastebin.com/Sj644xCW
